### ISSUE TITLE
Mypy reports missing library stubs

### ISSUE THREAD

**Issue by julosaure** [mar10/nutree#11]
Hi,

First, thanks for developing nutree, I started playing with it and the library is fantastic. Love the export to graph format in particular!

I have Mypy mentioning:
 error: Skipping analyzing "nutree": module is installed, but missing library stubs or py.typed marker  [import-untyped]

I wasn't able to figure out how to get rid of it. Is there anything needed?

Thanks

**Comment by mar10** [comment]
Thanks for reporting!
I am aware of current typing errors, although I use pylance in Vscode so far.
Running `mypy nutree` on the command line also lists those errors.
But I did not see the 'missing library stubs ' message. 
I'd think stub files are not required if the Python source is natively typed...

How did you generate the error message?

**Comment by julosaure** [comment]
Sure. I just run ```mypy app``` where app is my package, on the command line like you.
I have python 12 installed via uv for this app. I don't know if i's natively typed, that might be the issue. I will investigate.

**Comment by mar10** [comment]
See also #12 which improves typing (passing pyright 'standard' now)

**Comment by kayjan** [comment]
You need to add a py.typed file (empty contents) to your project to make the package PEP-561-aware. [Source](https://stackoverflow.com/questions/57785471/why-does-mypy-think-library-imports-are-missing)

**Comment by mar10** [comment]
Added with v0.10
