### ISSUE TITLE
Add `MODIFIED` to `DiffClassification`

### ISSUE THREAD

**Issue by acxz** [mar10/nutree#14]
Hello @mar10, I just want to say that this is a really great tree library! I especially love `diff()`, I haven't seen a better tree diff specification anywhere else.

I have a feature request concerning `diff()`, often times the difference in my tree is not a newly added node (`ADDED`), is not a removed node (`REMOVED`), not a change in parent node (`MOVED_TO`/`MOVED_HERE`), but rather a modification in the node's attributes/metadata (`MODIFIED`).

Would it be possible to add `MODIFIED` to `DiffClassification`, so as to relay the information that a node has been modified?

From the example on <https://nutree.readthedocs.io/en/latest/ug_diff.html>, if node `b11` was modified then we could have the following output:

```
Tree<"diff('T0', 'T1')">
├── A
│   ├── a1 - [Renumbered]
│   │   ├── a11 - [Removed]
│   │   ╰── a12 - [Order -1]
│   ╰── a2
│       ╰── a21 - [Added]
├── B
│   ╰── b1 - [Moved away]
╰── C - [Added]
    ╰── b1 - [Moved here]
        ╰── b11 - [Modified]
```

From a dot file perspective, modified nodes could have the another color (say orange) to differentiate from added and removed nodes.

There is also the case to consider where a node whose parent has changed, i.e. a `MOVED_TO`/`MOVED_HERE` node has also been modified. In such a case maybe an addition of `MODIFIED_AND_MOVED_TO`/`MODIFIED_AND_MOVED_HERE` is needed in `DiffClassification`. I can imagine something similar happening when a node has been modified and its child order changed.

An example of the case where a node has been both modified and moved (say the `b1` node):
```

Tree<"diff('T0', 'T1')">
├── A
│   ├── a1 - [Renumbered]
│   │   ├── a11 - [Removed]
│   │   ╰── a12 - [Order -1]
│   ╰── a2
│       ╰── a21 - [Added]
├── B
│   ╰── b1 - [Modified, Moved away]
╰── C - [Added]
    ╰── b1 - [Modified, Moved here]
        ╰── b11
```

Would a feature like this be feasible to implement?

[bigtree](https://bigtree.readthedocs.io) is another python library that serves many of the same use cases as nutree, and it does have support for displaying modified nodes in its [tree diff](https://bigtree.readthedocs.io/en/stable/bigtree/tree/helper/#bigtree.tree.helper.get_tree_diff). Unfortunately, its tree diff output doesn't keep track of both modified and moved nodes. It also tags moved information throughout the entire subtree causing an unnecessarily bulky diff output with respect to parent changes for a node. Basically I need a tree diff that can do what bigtree does and what nutree does together lol.

**Comment by mar10** [comment]
Thanks for the suggestion.

Improving the diff-functionality is planned, but I think it needs some more specification.

"node_1 is equal to node_2" can have multiple interpretations:

1. `node_1 is node_2` 
   This is never the case, since `Node` instances are unique.
2. `node_1.data is node_2.data`
   If the referenced objects are identical, they must be equal.
3. `node_1.data == node_2.data`
   The behavior depends on the object type. Strings are simply compared, other objects may implement `__eq__` 
4. `node_1.data_id == node_2.data_id`
    The data_id is derived from `hash(data)`, _when the node is added to the tree_ (unless it is explicitly passed to `add()`).
    One _could_ assume that the `data` instances where equal at the time the node was added.
5. `node_1 == node_2`
    This is implemented as `node_1.data == node_2.data` (see above)

In any case, we need to support a callback that allows custom comparison of data instances.

**Comment by acxz** [comment]
Thanks for taking the time to respond to this feature request!

> We need a definition of "two nodes have the same identity", that is different from "these nodes have different content".

I hear you. This statement right here is really the crux. I think if we have this concept, it should solve this issue.

I think we could leverage the following to solve this problem:
> `node_1 == node_2`
> This is implemented as node_1.data == node_2.data (see above)

What do you think about having `node_1.id` instead of `node_1.data_id`?

**Comment by mar10** [comment]
Not sure what you mean by 'node_1.id'? There is already a `node.node_id`, but this doesn't help. I added point 6. to clarify.

Could you explain your use case, please. How are you generating the two tree instances and how do modifications happen?

**Comment by mar10** [comment]
I added annotations for modified nodes (available with v0.11.0, [see here](https://nutree.readthedocs.io/en/latest/take_the_tour.html#diff))
Let me know if it works for you.

**Comment by acxz** [comment]
Yo this is dope actually. That's exactly what we needed to show. I do have one small nit, tho (I'm sorry...)

In your example you have the following:
![image](https://github.com/user-attachments/assets/f43cc7f7-22fe-4fd4-b059-e2be5ca78f15)

From this image, I understand that we have correctly identified that the Alice/Alicia node has been modified but we have that single modified node showing up in two places. I believe it makes more sense to show the modified node as a single node instead of two. i.e. like this:

![image](https://github.com/user-attachments/assets/888bb61d-86e4-4503-a3d6-2fe69b945e3c)
But of course with Alice/Alicia colorcoded to be shown as modified. However, in Alice/Alicia's case (unlike Dave), her graphviz label has changed as well. To account for this, can we have the label show up as `Alice->Alicia` on that single modified colorcoded node?

**Comment by mar10** [comment]
I added a few changes with v0.11.1 and it now looks like this:
https://nutree.readthedocs.io/en/latest/take_the_tour.html#diff

Note that a lot of the formatting must be done with node- and edge-mappers 
(see [sample code](https://github.com/mar10/nutree/blob/main/tests/make_sample_files.py))

**Comment by acxz** [comment]
Dude... This is it! This is some really great work!
Thank you so much for the quick iterations!
I think what you got here is a solid tree diff specification!

I'm just gonna summarize here for my own benefit, but I think its useful anyway.
- can show new nodes (get new parent relationship for free)
- can show removed nodes (get removed parent relationship for free)
- can show modified node
- can show moved nodes (essentially modified parent relationships)
