### ISSUE TITLE
Make use of generics

### ISSUE THREAD

**Issue by Viicos** [mar10/nutree#8]
Hi, thanks for this library. I'm experimenting with it to represent a tree like structure and seems to fit well.

I think it would be nice to make use of generics for the `Node` and `Tree` class, something like:

```python
NodeT = TypeVar("NodeT", bound=Node)

class Tree(Generic[NodeT]):
    def __init__(
        self,
        name: str | None = None,
        *,
        factory: type[NodeT] | None = None,
        ...
    ) -> None: ...

    def add_child(self, child: NodeT | Tree | Any, ...) -> NodeT: ...


DataT = TypeVar("DataT")


class Node(Generic[DataT]):
    def __init__(
        self,
        data: DataT,
        *,
        parent: Node,
        data_id: DataIdType | None = None,
        node_id: int | None = None,
        meta: dict = None,
    ): ...

    @property
    def data(self) -> DataT: ...

    def set_data(self, data: DataT, *, data_id=None, with_clones: bool = None) -> None: ...
```

I think most of the time people will create trees with the same node class, and with the same data type as well. I can work on a PR if you think this is a good idea.

**Comment by mar10** [comment]
Hi,
that would be an improvement, we can experiment with it. Let's see where it takes us. 
We need have tests and support for the [TypedTree](https://github.com/mar10/nutree/blob/main/nutree/typed_tree.py) as well. 
And also [deal with Python version 3.8+](https://pypi.org/project/typing-extensions/) somehow, I think.

**Comment by mar10** [comment]
Closed by #12

**Comment by sergei-maertens** [comment]
@Viicos and @mar10 I'd really like to thank you both for this library and the generic typing support, it's working wonderful so far. I'm doing a massive rewrite of one of our projects and nutree helps a ton.

Viicos - I am actually doing it an cleaning up the formio processing 😆

**Comment by Viicos** [comment]
I can't remember exactly what I was trying to solve with nutree, but glad to hear it actually works for open-forms! (Typing support for tree shapes with the current Python typing constructs is certainly tricky).
